language: cpp

cache: ccache

compiler: gcc

env:
  - PERL_CPANM_OPT="--mirror https://cpan.metacpan.org/"

addons:
  hosts:
    - 127.0.0.1.xip.io
    - alternate.127.0.0.1.xip.io

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get --yes update
        - sudo apt-get install --yes apache2-utils cmake cmake-data libev-dev libc-ares-dev php5-cgi wget zlib1g-dev
          # for speed, pre-install deps installed in `before_script` section as ubuntu packages
        - sudo apt-get install -qq cpanminus libfcgi-perl libfcgi-procmanager-perl libipc-signal-perl libjson-perl liblist-moreutils-perl libplack-perl libscope-guard-perl libtest-exception-perl libtest-tcp-perl libwww-perl libio-socket-ssl-perl
        - misc/install-perl-module.pl Path::Tiny
        - misc/install-perl-module.pl Starlet
        # install libuv, openssl 1.0.2, nghttp2, curl with nghttp2
        - curl -L https://github.com/libuv/libuv/archive/v1.0.0.tar.gz | tar xzf -
        - (cd libuv-1.0.0 && ./autogen.sh && ./configure --prefix=/usr/local && make -j 2 && sudo make install)
        - curl -L https://www.openssl.org/source/openssl-1.0.2n.tar.gz | tar xzf -
        - (cd openssl-1.0.2n && ./config --prefix=/usr/local && make -j 2 && sudo make install)
        - curl -L https://github.com/nghttp2/nghttp2/releases/download/v1.28.0/nghttp2-1.28.0.tar.gz | tar xzf -
        - (cd nghttp2-1.28.0 && ./configure --prefix=/usr/local --disable-threads --disable-shared --enable-app && make -j 2 && sudo make install)
        - curl -L https://curl.haxx.se/download/curl-7.50.0.tar.gz | tar xzf -
        - (cd curl-7.50.0 && ./configure --prefix=/usr/local --with-nghttp2 --disable-shared && make -j 2 && sudo make install)
      script: &s
        - cmake -DWITH_MRUBY=ON .
        - make all
        - make check
        - sudo make check-as-root
